name: Connect Backlog
on:
  pull_request:
    branches:
      - master
    types: [edited]
jobs:
  extract_issue_id:
    runs-on: ubuntu-latest
    steps:
      - id: output-set
        uses: actions/github-script@v5
        with:
          script: |
            const pr_body = context.payload.pull_request.body
            const bl_pat = pr_body.match(/https:\/\/ventus-inc\.backlog\.com\/view\/(VENTUS_ADMIN-[0-9]+)/)[1]
            console.log(bl_pat)
            return bl_pat
      - run: |
          if [[ ${{steps.output-set.outputs.result}} != "" ]]; then
            echo hello
          fi
