name: Connect Backlog
on:
  pull_request:
    branches:
      - master
    types: [edited]
jobs:
  extract_issue_id:
    runs-on: ubuntu-latest
    steps:
      - id: issue-id
        name: Extract Issue ID
        uses: actions/github-script@v5
        with:
          script: |
            const pr_body = context.payload.pull_request.body
            const bl_pat = pr_body.match(/https:\/\/ventus-inc\.backlog\.com\/view\/(VENTUS_ADMIN-[0-9]+)/)
            console.log(bl_pat)
            if (!!bl_pat) {
              return bl_pat[1]
            }
      - name: Update Backlog Issue
        if: ${{steps.issue-id.outputs.result != null && steps.issue-id.outputs.result != ''}}
        run: |
          echo ${{steps.issue-id.outputs.result}}
          curl --location --request GET 'https://ventus-inc.backlog.com/api/v2/issues/${${{steps.issue-id.outputs.result}}}?apiKey=${{secrets.BACKLOG_USER_API_KEY}}'
